apiVersion: v1
kind: Service
metadata:
  name: pdr-ms-cobranza-cliente
  namespace: cobranza

spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: pdr-ms-cobranza-cliente
  type: NodePort
