package com.pdr.starter.cliente.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Generated by BS2
 */
@Entity
@Table(name = "CBZ_ARBOL_GESTION_TITULOS", schema = "CBZPAR")
public class CbzArbolGestionTitulosModel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idArbolTitulos;
	private String arbolDescripcion;
	private Set<CbzArbolGestionModel> cbzArbolGestions = new HashSet<CbzArbolGestionModel>(0);

	public CbzArbolGestionTitulosModel() {
	}

	public CbzArbolGestionTitulosModel(int idArbolTitulos) {
		this.idArbolTitulos = idArbolTitulos;
	}

	public CbzArbolGestionTitulosModel(int idArbolTitulos, String arbolDescripcion, Set<CbzArbolGestionModel> cbzArbolGestions) {
		this.idArbolTitulos = idArbolTitulos;
		this.arbolDescripcion = arbolDescripcion;
		this.cbzArbolGestions = cbzArbolGestions;
	}

	@Id

	@Column(name = "ID_ARBOL_TITULOS", unique = true, nullable = false, precision = 8, scale = 0)
	public int getIdArbolTitulos() {
		return this.idArbolTitulos;
	}

	public void setIdArbolTitulos(int idArbolTitulos) {
		this.idArbolTitulos = idArbolTitulos;
	}

	@Column(name = "ARBOL_DESCRIPCION", length = 200)
	public String getArbolDescripcion() {
		return this.arbolDescripcion;
	}

	public void setArbolDescripcion(String arbolDescripcion) {
		this.arbolDescripcion = arbolDescripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cbzArbolGestionTitulos")
	public Set<CbzArbolGestionModel> getCbzArbolGestions() {
		return this.cbzArbolGestions;
	}

	public void setCbzArbolGestions(Set<CbzArbolGestionModel> cbzArbolGestions) {
		this.cbzArbolGestions = cbzArbolGestions;
	}

}
