package com.pdr.starter.cliente.model;
// Generated 18-08-2020 21:09:41 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CbzArbolGestionNotificacion generated by hbm2java
 */
@Entity
@Table(name = "CBZ_ARBOL_GESTION_NOTIFICACION", schema = "CBZPAR")
public class CbzArbolGestionNotificacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idGestNotificacion;
	private CbzGestionCobranzaHistModel cbzGestionCobranzaHist;
	private CbzArbolGestionNotifEstado cbzArbolGestionNotifEstado;
	private String notifUsuarioOrig;
	private BigDecimal notifIdPerfilDest;
	private Date notifFecha;

	public CbzArbolGestionNotificacion() {
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ID_ARBOL_GESTION_NOTIFICACION")
	@SequenceGenerator(name = "ID_ARBOL_GESTION_NOTIFICACION", allocationSize = 1, sequenceName = "SEQ_ARBOL_GESTION_NOTIFICACION", schema = "CBZPAR")
	@Column(name = "ID_GEST_NOTIFICACION", unique = true, nullable = false, precision = 21, scale = 0)
	public BigDecimal getIdGestNotificacion() {
		return this.idGestNotificacion;
	}

	public void setIdGestNotificacion(BigDecimal idGestNotificacion) {
		this.idGestNotificacion = idGestNotificacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_GEST_COBHIST", nullable = false)
	public CbzGestionCobranzaHistModel getCbzGestionCobranzaHist() {
		return this.cbzGestionCobranzaHist;
	}

	public void setCbzGestionCobranzaHist(CbzGestionCobranzaHistModel cbzGestionCobranzaHist) {
		this.cbzGestionCobranzaHist = cbzGestionCobranzaHist;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ESTADO_NOTIFICACION", nullable = false)
	public CbzArbolGestionNotifEstado getCbzArbolGestionNotifEstado() {
		return this.cbzArbolGestionNotifEstado;
	}

	public void setCbzArbolGestionNotifEstado(CbzArbolGestionNotifEstado cbzArbolGestionNotifEstado) {
		this.cbzArbolGestionNotifEstado = cbzArbolGestionNotifEstado;
	}

	@Column(name = "NOTIF_USUARIO_ORIG", length = 100)
	public String getNotifUsuarioOrig() {
		return this.notifUsuarioOrig;
	}

	public void setNotifUsuarioOrig(String notifUsuarioOrig) {
		this.notifUsuarioOrig = notifUsuarioOrig;
	}

	@Column(name = "NOTIF_ID_PERFIL_DEST", nullable = false, precision = 22, scale = 0)
	public BigDecimal getNotifIdPerfilDest() {
		return this.notifIdPerfilDest;
	}

	public void setNotifIdPerfilDest(BigDecimal notifIdPerfilDest) {
		this.notifIdPerfilDest = notifIdPerfilDest;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NOTIF_FECHA", length = 7)
	public Date getNotifFecha() {
		return notifFecha;
	}

	public void setNotifFecha(Date notifFecha) {
		this.notifFecha = notifFecha;
	}

}
