package com.pdr.starter.cliente.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Generated by BS2
 */
@Entity
@Table(name = "CBZ_ARBOL_GESTION_TIPO_DATO", schema = "CBZPAR")
public class CbzArbolGestionTipoDatoModel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idArbTipoDato;
	private String tipoArbDescripcion;
	private Set<CbzArbolGestionModel> cbzArbolGestions = new HashSet<CbzArbolGestionModel>(0);

	public CbzArbolGestionTipoDatoModel() {
	}

	public CbzArbolGestionTipoDatoModel(int idArbTipoDato) {
		this.idArbTipoDato = idArbTipoDato;
	}

	public CbzArbolGestionTipoDatoModel(int idArbTipoDato, String tipoArbDescripcion,
			Set<CbzArbolGestionModel> cbzArbolGestions) {
		this.idArbTipoDato = idArbTipoDato;
		this.tipoArbDescripcion = tipoArbDescripcion;
		this.cbzArbolGestions = cbzArbolGestions;
	}

	@Id

	@Column(name = "ID_ARB_TIPO_DATO", unique = true, nullable = false, precision = 8, scale = 0)
	public int getIdArbTipoDato() {
		return this.idArbTipoDato;
	}

	public void setIdArbTipoDato(int idArbTipoDato) {
		this.idArbTipoDato = idArbTipoDato;
	}

	@Column(name = "TIPO_ARB_DESCRIPCION", length = 100)
	public String getTipoArbDescripcion() {
		return this.tipoArbDescripcion;
	}

	public void setTipoArbDescripcion(String tipoArbDescripcion) {
		this.tipoArbDescripcion = tipoArbDescripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cbzArbolGestionTipoDato")
	public Set<CbzArbolGestionModel> getCbzArbolGestions() {
		return this.cbzArbolGestions;
	}

	public void setCbzArbolGestions(Set<CbzArbolGestionModel> cbzArbolGestions) {
		this.cbzArbolGestions = cbzArbolGestions;
	}

}
