package com.pdr.starter.cliente.model;
// Generated 18-08-2020 21:09:41 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CbzArbolGestionNotifEstado generated by hbm2java
 */
@Entity
@Table(name = "CBZ_ARBOL_GESTION_NOTIF_ESTADO", schema = "CBZPAR")
public class CbzArbolGestionNotifEstado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idEstadoNotificacion;
	private String notifDescripcion;
	private BigDecimal activo;
	private Set<CbzArbolGestionNotificacion> cbzArbolGestionNotificacions = new HashSet<>(0);

	public CbzArbolGestionNotifEstado() {
	}

	public CbzArbolGestionNotifEstado(int idEstadoNotificacion) {
		this.idEstadoNotificacion = idEstadoNotificacion;
	}

	public CbzArbolGestionNotifEstado(int idEstadoNotificacion, String notifDescripcion, BigDecimal activo,
			Set<CbzArbolGestionNotificacion> cbzArbolGestionNotificacions) {
		this.idEstadoNotificacion = idEstadoNotificacion;
		this.notifDescripcion = notifDescripcion;
		this.activo = activo;
		this.cbzArbolGestionNotificacions = cbzArbolGestionNotificacions;
	}

	@Id
	@Column(name = "ID_ESTADO_NOTIFICACION", unique = true, nullable = false, precision = 8, scale = 0)
	public int getIdEstadoNotificacion() {
		return this.idEstadoNotificacion;
	}

	public void setIdEstadoNotificacion(int idEstadoNotificacion) {
		this.idEstadoNotificacion = idEstadoNotificacion;
	}

	@Column(name = "NOTIF_DESCRIPCION", length = 100)
	public String getNotifDescripcion() {
		return this.notifDescripcion;
	}

	public void setNotifDescripcion(String notifDescripcion) {
		this.notifDescripcion = notifDescripcion;
	}

	@Column(name = "ACTIVO", precision = 22, scale = 0)
	public BigDecimal getActivo() {
		return this.activo;
	}

	public void setActivo(BigDecimal activo) {
		this.activo = activo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cbzArbolGestionNotifEstado")
	public Set<CbzArbolGestionNotificacion> getCbzArbolGestionNotificacions() {
		return this.cbzArbolGestionNotificacions;
	}

	public void setCbzArbolGestionNotificacions(Set<CbzArbolGestionNotificacion> cbzArbolGestionNotificacions) {
		this.cbzArbolGestionNotificacions = cbzArbolGestionNotificacions;
	}

}
