package com.pdr.starter.cliente.model;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CbzCriterioDos generated by BS2
 */
@Entity
@Table(name = "CBZ_CRITERIO_DOS", schema = "CBZPAR")
public class CbzCriterioDosModel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idCdCriterioDos;
	private CobFasesModel cobFases;
	private CbzPeriodoConfModel cbzPeriodoConf;
	private String cdNombre;
	private String cdOrdenamiento;
	private String cdTipoAsignacion;
	private boolean cdActivo;
	private Set<CbzCriterioDosRenegAsigModel> cbzCriterioDosRenegAsigs = new HashSet<>(0);

	public CbzCriterioDosModel() {
	}

	

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ID_SEQUENCE_CRITERIO_DOS")
	@SequenceGenerator(name = "ID_SEQUENCE_CRITERIO_DOS", allocationSize = 1, sequenceName = "SEQ_CBZ_CRITERIO_DOS", schema = "CBZPAR")
	@Column(name = "ID_CD_CRITERIO_DOS", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdCdCriterioDos() {
		return this.idCdCriterioDos;
	}

	public void setIdCdCriterioDos(BigDecimal idCdCriterioDos) {
		this.idCdCriterioDos = idCdCriterioDos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "FASE_COD", referencedColumnName = "FASE_COD"),
			@JoinColumn(name = "EMPR_COD", referencedColumnName = "EMPR_COD") })
	public CobFasesModel getCobFases() {
		return this.cobFases;
	}

	public void setCobFases(CobFasesModel cobFases) {
		this.cobFases = cobFases;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CPC_PERIODO", nullable = false)
	public CbzPeriodoConfModel getCbzPeriodoConf() {
		return this.cbzPeriodoConf;
	}

	public void setCbzPeriodoConf(CbzPeriodoConfModel cbzPeriodoConf) {
		this.cbzPeriodoConf = cbzPeriodoConf;
	}
	
	@Column(name = "CD_NOMBRE", nullable = false, length = 100)
	public String getCdNombre() {
		return this.cdNombre;
	}

	public void setCdNombre(String cdNombre) {
		this.cdNombre = cdNombre;
	}

	@Column(name = "CD_ORDENAMIENTO", nullable = false, length = 50)
	public String getCdOrdenamiento() {
		return this.cdOrdenamiento;
	}

	public void setCdOrdenamiento(String cdOrdenamiento) {
		this.cdOrdenamiento = cdOrdenamiento;
	}

	@Column(name = "CD_TIPO_ASIGNACION", nullable = false, length = 50)
	public String getCdTipoAsignacion() {
		return this.cdTipoAsignacion;
	}

	public void setCdTipoAsignacion(String cdTipoAsignacion) {
		this.cdTipoAsignacion = cdTipoAsignacion;
	}
	
	@Column(name = "CD_ACTIVO", nullable = false, precision = 1, scale = 0)
	public boolean isCdActivo() {
		return this.cdActivo;
	}

	public void setCdActivo(boolean cdActivo) {
		this.cdActivo = cdActivo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cbzCriterioDos")
	public Set<CbzCriterioDosRenegAsigModel> getCbzCriterioDosRenegAsigs() {
		return this.cbzCriterioDosRenegAsigs;
	}

	public void setCbzCriterioDosRenegAsigs(Set<CbzCriterioDosRenegAsigModel> cbzCriterioDosRenegAsigs) {
		this.cbzCriterioDosRenegAsigs = cbzCriterioDosRenegAsigs;
	}

}
