package com.pdr.starter.cliente.model;
// Generated 20-07-2020 10:42:05 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Generated by BS2
 */
@Entity
@Table(name = "CBZ_CANALES", schema = "CBZPAR")
public class CbzCanalesModel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idCanal;
	private String canalDescripcion;
	private BigDecimal canalActivo;
	private Set<CbzCanalesUserprofileModel> cbzCanalesUserprofiles = new HashSet<CbzCanalesUserprofileModel>(0);
	private Set<CbzArbolGestionModel> cbzArbolGestions = new HashSet<CbzArbolGestionModel>(0);

	public CbzCanalesModel() {
	}

	public CbzCanalesModel(int idCanal, String canalDescripcion, BigDecimal canalActivo) {
		this.idCanal = idCanal;
		this.canalDescripcion = canalDescripcion;
		this.canalActivo = canalActivo;
	}

	public CbzCanalesModel(int idCanal, String canalDescripcion, BigDecimal canalActivo,
			Set<CbzCanalesUserprofileModel> cbzCanalesUserprofiles, Set<CbzArbolGestionModel> cbzArbolGestions) {
		this.idCanal = idCanal;
		this.canalDescripcion = canalDescripcion;
		this.canalActivo = canalActivo;
		this.cbzCanalesUserprofiles = cbzCanalesUserprofiles;
		this.cbzArbolGestions = cbzArbolGestions;
	}

	@Id

	@Column(name = "ID_CANAL", unique = true, nullable = false, precision = 8, scale = 0)
	public int getIdCanal() {
		return this.idCanal;
	}

	public void setIdCanal(int idCanal) {
		this.idCanal = idCanal;
	}

	@Column(name = "CANAL_DESCRIPCION", nullable = false, length = 100)
	public String getCanalDescripcion() {
		return this.canalDescripcion;
	}

	public void setCanalDescripcion(String canalDescripcion) {
		this.canalDescripcion = canalDescripcion;
	}

	@Column(name = "CANAL_ACTIVO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCanalActivo() {
		return this.canalActivo;
	}

	public void setCanalActivo(BigDecimal canalActivo) {
		this.canalActivo = canalActivo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cbzCanales")
	public Set<CbzCanalesUserprofileModel> getCbzCanalesUserprofiles() {
		return this.cbzCanalesUserprofiles;
	}

	public void setCbzCanalesUserprofiles(Set<CbzCanalesUserprofileModel> cbzCanalesUserprofiles) {
		this.cbzCanalesUserprofiles = cbzCanalesUserprofiles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cbzCanales")
	public Set<CbzArbolGestionModel> getCbzArbolGestions() {
		return this.cbzArbolGestions;
	}

	public void setCbzArbolGestions(Set<CbzArbolGestionModel> cbzArbolGestions) {
		this.cbzArbolGestions = cbzArbolGestions;
	}

}
