package com.pdr.starter.cliente.model;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CbzCriterioDosRenegAsig generated by BS2
 */
@Entity
@Table(name = "CBZ_CRITERIO_DOS_RENEG_ASIG", schema = "CBZPAR")
public class CbzCriterioDosRenegAsigModel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idCdRenegAsig;
	private CbzCriterioDosModel cbzCriterioDos;
	private Integer cdPorcAsignacion;
	private Integer cdNumeroContratos;
	private Date cdFechaCreacion;
	private String emplRut;
	private String emplNombreCompleto;

	public CbzCriterioDosRenegAsigModel() {
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ID_SEQUENCE_CRITERIO_DOS_RENEG_ASIG")
	@SequenceGenerator(name = "ID_SEQUENCE_CRITERIO_DOS_RENEG_ASIG", allocationSize = 1, sequenceName = "SEQ_CBZ_CRITERIO_DOS_RENEG_ASIG", schema = "CBZPAR")
	@Column(name = "ID_CD_RENEG_ASIG", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdCdRenegAsig() {
		return this.idCdRenegAsig;
	}

	public void setIdCdRenegAsig(BigDecimal idCdRenegAsig) {
		this.idCdRenegAsig = idCdRenegAsig;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CD_CRITERIO_DOS", nullable = false)
	public CbzCriterioDosModel getCbzCriterioDos() {
		return this.cbzCriterioDos;
	}

	public void setCbzCriterioDos(CbzCriterioDosModel cbzCriterioDos) {
		this.cbzCriterioDos = cbzCriterioDos;
	}

	@Column(name = "CD_PORC_ASIGNACION", precision = 8, scale = 0)
	public Integer getCdPorcAsignacion() {
		return this.cdPorcAsignacion;
	}

	public void setCdPorcAsignacion(Integer cdPorcAsignacion) {
		this.cdPorcAsignacion = cdPorcAsignacion;
	}

	@Column(name = "CD_NUMERO_CONTRATOS", precision = 8, scale = 0)
	public Integer getCdNumeroContratos() {
		return this.cdNumeroContratos;
	}

	public void setCdNumeroContratos(Integer cdNumeroContratos) {
		this.cdNumeroContratos = cdNumeroContratos;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CD_FECHA_CREACION", length = 7)
	public Date getCdFechaCreacion() {
		return this.cdFechaCreacion;
	}

	public void setCdFechaCreacion(Date cdFechaCreacion) {
		this.cdFechaCreacion = cdFechaCreacion;
	}

	@Column(name = "EMPL_RUT", nullable = false, length = 15)
	public String getEmplRut() {
		return this.emplRut;
	}

	public void setEmplRut(String emplRut) {
		this.emplRut = emplRut;
	}

	@Column(name = "EMPL_NOMBRE_COMPLETO", nullable = false, length = 75)
	public String getEmplNombreCompleto() {
		return this.emplNombreCompleto;
	}

	public void setEmplNombreCompleto(String emplNombreCompleto) {
		this.emplNombreCompleto = emplNombreCompleto;
	}

}
