package com.pdr.starter.cliente.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CbzCriterioUno generated by BS2
 */
@Entity
@Table(name = "CBZ_CRITERIO_UNO", schema = "CBZPAR")
public class CbzCriterioUnoModel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idCuCriterioUno;
	private CbzPeriodoConfModel cbzPeriodoConf;
	private Long cuRenegDesde;
	private Long cuRenegHasta;
	private Long cuCuotasPagDesde;
	private Long cuCuotasPagHasta;
	private String cuAsigNombre;
	private Boolean cuActivo;
	private String cuOrdenamiento;
	private String cuUsernameCreacion;
	private Date cuFechaCreacion;
	private String cuUsernameMod;
	private Date cuFechaMod;
	private String cuTipoAsignacion;
	private Set<CbzCriterioUnoRenegAsigModel> cbzCriterioUnoRenegAsigs = new HashSet<CbzCriterioUnoRenegAsigModel>(0);
	private Set<CbzCriterioUnoFasesModel> cbzCriterioUnoFases = new HashSet<CbzCriterioUnoFasesModel>(0);

	public CbzCriterioUnoModel() {
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ID_SEQUENCE_CRITERIO_UNO")
	@SequenceGenerator(name = "ID_SEQUENCE_CRITERIO_UNO", allocationSize = 1, sequenceName = "SEQ_CBZ_CRITERIO_UNO", schema = "CBZPAR")
	@Column(name = "ID_CU_CRITERIO_UNO", unique = true, nullable = false, precision = 16, scale = 0)
	public long getIdCuCriterioUno() {
		return this.idCuCriterioUno;
	}

	public void setIdCuCriterioUno(long idCuCriterioUno) {
		this.idCuCriterioUno = idCuCriterioUno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CPC_PERIODO", nullable = false)
	public CbzPeriodoConfModel getCbzPeriodoConf() {
		return this.cbzPeriodoConf;
	}

	public void setCbzPeriodoConf(CbzPeriodoConfModel cbzPeriodoConf) {
		this.cbzPeriodoConf = cbzPeriodoConf;
	}

	@Column(name = "CU_RENEG_DESDE", precision = 10, scale = 0)
	public Long getCuRenegDesde() {
		return this.cuRenegDesde;
	}

	public void setCuRenegDesde(Long cuRenegDesde) {
		this.cuRenegDesde = cuRenegDesde;
	}

	@Column(name = "CU_RENEG_HASTA", precision = 10, scale = 0)
	public Long getCuRenegHasta() {
		return this.cuRenegHasta;
	}

	public void setCuRenegHasta(Long cuRenegHasta) {
		this.cuRenegHasta = cuRenegHasta;
	}

	@Column(name = "CU_CUOTAS_PAG_DESDE", precision = 10, scale = 0)
	public Long getCuCuotasPagDesde() {
		return this.cuCuotasPagDesde;
	}

	public void setCuCuotasPagDesde(Long cuCuotasPagDesde) {
		this.cuCuotasPagDesde = cuCuotasPagDesde;
	}

	@Column(name = "CU_CUOTAS_PAG_HASTA", precision = 10, scale = 0)
	public Long getCuCuotasPagHasta() {
		return this.cuCuotasPagHasta;
	}

	public void setCuCuotasPagHasta(Long cuCuotasPagHasta) {
		this.cuCuotasPagHasta = cuCuotasPagHasta;
	}

	@Column(name = "CU_ASIG_NOMBRE", length = 100)
	public String getCuAsigNombre() {
		return this.cuAsigNombre;
	}

	public void setCuAsigNombre(String cuAsigNombre) {
		this.cuAsigNombre = cuAsigNombre;
	}

	@Column(name = "CU_ACTIVO", precision = 1, scale = 0)
	public Boolean getCuActivo() {
		return this.cuActivo;
	}

	public void setCuActivo(Boolean cuActivo) {
		this.cuActivo = cuActivo;
	}

	@Column(name = "CU_ORDENAMIENTO", length = 100)
	public String getCuOrdenamiento() {
		return this.cuOrdenamiento;
	}

	public void setCuOrdenamiento(String cuOrdenamiento) {
		this.cuOrdenamiento = cuOrdenamiento;
	}

	@Column(name = "CU_USERNAME_CREACION", length = 100)
	public String getCuUsernameCreacion() {
		return this.cuUsernameCreacion;
	}

	public void setCuUsernameCreacion(String cuUsernameCreacion) {
		this.cuUsernameCreacion = cuUsernameCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CU_FECHA_CREACION", length = 7)
	public Date getCuFechaCreacion() {
		return this.cuFechaCreacion;
	}

	public void setCuFechaCreacion(Date cuFechaCreacion) {
		this.cuFechaCreacion = cuFechaCreacion;
	}

	@Column(name = "CU_USERNAME_MOD", length = 100)
	public String getCuUsernameMod() {
		return this.cuUsernameMod;
	}

	public void setCuUsernameMod(String cuUsernameMod) {
		this.cuUsernameMod = cuUsernameMod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CU_FECHA_MOD", length = 7)
	public Date getCuFechaMod() {
		return this.cuFechaMod;
	}

	public void setCuFechaMod(Date cuFechaMod) {
		this.cuFechaMod = cuFechaMod;
	}

	@Column(name = "CU_TIPO_ASIGNACION", nullable = false, length = 50)
	public String getCuTipoAsignacion() {
		return this.cuTipoAsignacion;
	}

	public void setCuTipoAsignacion(String cuTipoAsignacion) {
		this.cuTipoAsignacion = cuTipoAsignacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cbzCriterioUno")
	public Set<CbzCriterioUnoRenegAsigModel> getCbzCriterioUnoRenegAsigs() {
		return this.cbzCriterioUnoRenegAsigs;
	}

	public void setCbzCriterioUnoRenegAsigs(Set<CbzCriterioUnoRenegAsigModel> cbzCriterioUnoRenegAsigs) {
		this.cbzCriterioUnoRenegAsigs = cbzCriterioUnoRenegAsigs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cbzCriterioUno")
	public Set<CbzCriterioUnoFasesModel> getCbzCriterioUnoFases() {
		return this.cbzCriterioUnoFases;
	}

	public void setCbzCriterioUnoFases(Set<CbzCriterioUnoFasesModel> cbzCriterioUnoFases) {
		this.cbzCriterioUnoFases = cbzCriterioUnoFases;
	}

}
