package com.pdr.starter.cliente.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Generated by BS2
 */
@Entity
@Table(name = "CBZ_DATOS_DEMOGRAFICOS_SECU", schema = "CBZPAR")
public class CbzDatosDemograficosSecuModel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private CbzDatosDemograficosSecuIdModel id;
	private VtaContratosModel vtaContratos;

	public CbzDatosDemograficosSecuModel() {
	}

	public CbzDatosDemograficosSecuModel(CbzDatosDemograficosSecuIdModel id, VtaContratosModel vtaContratos) {
		this.id = id;
		this.vtaContratos = vtaContratos;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idDatosSecundarios", column = @Column(name = "ID_DATOS_SECUNDARIOS", precision = 22)),
			@AttributeOverride(name = "vtopCodCont", column = @Column(name = "VTOP_COD_CONT", nullable = false, precision = 23, scale = 0)),
			@AttributeOverride(name = "dsecDireccion", column = @Column(name = "DSEC_DIRECCION", length = 500)),
			@AttributeOverride(name = "dsecCelular", column = @Column(name = "DSEC_CELULAR", length = 15)),
			@AttributeOverride(name = "dsecEmailSec", column = @Column(name = "DSEC_EMAIL_SEC", length = 200)),
			@AttributeOverride(name = "dsecEmailTerc", column = @Column(name = "DSEC_EMAIL_TERC", length = 100)) })
	public CbzDatosDemograficosSecuIdModel getId() {
		return this.id;
	}

	public void setId(CbzDatosDemograficosSecuIdModel id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VTOP_COD_CONT", nullable = false, insertable = false, updatable = false)
	public VtaContratosModel getVtaContratos() {
		return this.vtaContratos;
	}

	public void setVtaContratos(VtaContratosModel vtaContratos) {
		this.vtaContratos = vtaContratos;
	}

}
