package com.pdr.starter.cliente.model;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Generated by BS2
 */
@Entity
@Table(name = "CBZ_ESTADO_AUTORIZA", schema = "CBZPAR")
public class CbzEstadoAutoriza implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idEstadoAutoriza;
	private CbzEstadoSimulacionModel cbzEstadoSimulacion;
	private BigDecimal idProfile;
	

	public CbzEstadoAutoriza() {
	}

	public CbzEstadoAutoriza(int idEstadoAutoriza) {
		this.idEstadoAutoriza = idEstadoAutoriza;
	}

	@Id
	@Column(name = "ID_ESTADO_AUTORIZA", unique = true, nullable = false, precision = 8, scale = 0)
	public int getIdEstadoAutoriza() {
		return this.idEstadoAutoriza;
	}

	public void setIdEstadoAutoriza(int idEstadoAutoriza) {
		this.idEstadoAutoriza = idEstadoAutoriza;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ESTADO_SIMULACION")
	public CbzEstadoSimulacionModel getCbzEstadoSimulacion() {
		return this.cbzEstadoSimulacion;
	}

	public void setCbzEstadoSimulacion(CbzEstadoSimulacionModel cbzEstadoSimulacion) {
		this.cbzEstadoSimulacion = cbzEstadoSimulacion;
	}

	@Column(name = "ID_PROFILE", precision = 22, scale = 0)
	public BigDecimal getIdProfile() {
		return this.idProfile;
	}

	public void setIdProfile(BigDecimal idProfile) {
		this.idProfile = idProfile;
	}

}
