package com.pdr.starter.cliente.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Generated by BS2
 */
@Entity
@Table(name = "CBZ_ESTADO_SIMULACION", schema = "CBZPAR")
public class CbzEstadoSimulacionModel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idEstadoSimulacion;
	private String estSimuDescripcion;
	private Boolean estSimuActivo;
	private Set<CbzEstadoAutoriza> cbzEstadoAutorizas = new HashSet<CbzEstadoAutoriza>(0);
	private Set<CbzSimulacionModel> cbzSimulacions = new HashSet<CbzSimulacionModel>(0);

	public CbzEstadoSimulacionModel() {
	}

	public CbzEstadoSimulacionModel(int idEstadoSimulacion) {
		this.idEstadoSimulacion = idEstadoSimulacion;
	}

	public CbzEstadoSimulacionModel(int idEstadoSimulacion, String estSimuDescripcion, Boolean estSimuActivo,
			Set<CbzEstadoAutoriza> cbzEstadoAutorizas, Set<CbzSimulacionModel> cbzSimulacions) {
		this.idEstadoSimulacion = idEstadoSimulacion;
		this.estSimuDescripcion = estSimuDescripcion;
		this.estSimuActivo = estSimuActivo;
		this.cbzEstadoAutorizas = cbzEstadoAutorizas;
		this.cbzSimulacions = cbzSimulacions;
	}

	@Id

	@Column(name = "ID_ESTADO_SIMULACION", unique = true, nullable = false, precision = 8, scale = 0)
	public int getIdEstadoSimulacion() {
		return this.idEstadoSimulacion;
	}

	public void setIdEstadoSimulacion(int idEstadoSimulacion) {
		this.idEstadoSimulacion = idEstadoSimulacion;
	}

	@Column(name = "EST_SIMU_DESCRIPCION", length = 100)
	public String getEstSimuDescripcion() {
		return this.estSimuDescripcion;
	}

	public void setEstSimuDescripcion(String estSimuDescripcion) {
		this.estSimuDescripcion = estSimuDescripcion;
	}

	@Column(name = "EST_SIMU_ACTIVO", precision = 1, scale = 0)
	public Boolean getEstSimuActivo() {
		return this.estSimuActivo;
	}

	public void setEstSimuActivo(Boolean estSimuActivo) {
		this.estSimuActivo = estSimuActivo;
	}


	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cbzEstadoSimulacion")
	public Set<CbzEstadoAutoriza> getCbzEstadoAutorizas() {
		return this.cbzEstadoAutorizas;
	}

	public void setCbzEstadoAutorizas(Set<CbzEstadoAutoriza> cbzEstadoAutorizas) {
		this.cbzEstadoAutorizas = cbzEstadoAutorizas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cbzEstadoSimulacion")
	public Set<CbzSimulacionModel> getCbzSimulacions() {
		return this.cbzSimulacions;
	}

	public void setCbzSimulacions(Set<CbzSimulacionModel> cbzSimulacions) {
		this.cbzSimulacions = cbzSimulacions;
	}

}
