package com.pdr.starter.cliente.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Generated by BS2
 */
@Entity
@Table(name = "CBZ_GESTION_COBRANZA_HIST", schema = "CBZPAR")
public class CbzGestionCobranzaHistModel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long idGestCobhist;
	private CobCatalogoPgreModel pgreCatpSec;
	private Date cobhistGestionFecha;
	private String cobhistTipoProxGestion;
	private boolean cobhistReqProxGestion;
	private Date cobhistFechaProxGestion;
	private String cobhistObservacion;
	private String cobhistNombreEjecutivo;
	private String cobhistResultado;
	private String cobhistCanal;
	private String cobhistPersonaContacto;
	private boolean cobhistReqMotorista;
	private Date cobhistFechaVisitaMoto;
	private Set<CbzResultadoArbolGestionModel> cbzResultadoArbolGestions = new HashSet<>(0);
	private Set<CbzArbolGestionNotificacion> cbzArbolGestionNotificacions = new HashSet<>(0);

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ID_SEQUENCE_GESTION_COBRANZA_HIST")
	@SequenceGenerator(name = "ID_SEQUENCE_GESTION_COBRANZA_HIST", allocationSize = 1, sequenceName = "SEQ_GESTION_COBRANZA_HIST", schema = "CBZPAR")
	@Column(name = "ID_GEST_COBHIST", unique = true, nullable = false, precision = 16, scale = 0)
	public Long getIdGestCobhist() {
		return this.idGestCobhist;
	}

	public void setIdGestCobhist(Long idGestCobhist) {
		this.idGestCobhist = idGestCobhist;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PGRE_CATP_SEC", nullable = false)
	public CobCatalogoPgreModel getPgreCatpSec() {
		return this.pgreCatpSec;
	}

	public void setPgreCatpSec(CobCatalogoPgreModel pgreCatpSec) {
		this.pgreCatpSec = pgreCatpSec;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "COBHIST_GESTION_FECHA", length = 7)
	public Date getCobhistGestionFecha() {
		return this.cobhistGestionFecha;
	}

	public void setCobhistGestionFecha(Date cobhistGestionFecha) {
		this.cobhistGestionFecha = cobhistGestionFecha;
	}

	@Column(name = "COBHIST_TIPO_PROX_GESTION", length = 100)
	public String getCobhistTipoProxGestion() {
		return this.cobhistTipoProxGestion;
	}

	public void setCobhistTipoProxGestion(String cobhistTipoProxGestion) {
		this.cobhistTipoProxGestion = cobhistTipoProxGestion;
	}

	@Column(name = "COBHIST_REQ_PROX_GESTION", nullable = false, precision = 1, scale = 0)
	public boolean isCobhistReqProxGestion() {
		return this.cobhistReqProxGestion;
	}

	public void setCobhistReqProxGestion(boolean cobhistReqProxGestion) {
		this.cobhistReqProxGestion = cobhistReqProxGestion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "COBHIST_FECHA_PROX_GESTION", length = 7)
	public Date getCobhistFechaProxGestion() {
		return this.cobhistFechaProxGestion;
	}

	public void setCobhistFechaProxGestion(Date cobhistFechaProxGestion) {
		this.cobhistFechaProxGestion = cobhistFechaProxGestion;
	}

	@Column(name = "COBHIST_OBSERVACION", length = 100)
	public String getCobhistObservacion() {
		return this.cobhistObservacion;
	}

	public void setCobhistObservacion(String cobhistObservacion) {
		this.cobhistObservacion = cobhistObservacion;
	}
	
	@Column(name = "COBHIST_NOMBRE_EJECUTIVO", length = 100)
	public String getCobhistNombreEjecutivo() {
		return this.cobhistNombreEjecutivo;
	}

	public void setCobhistNombreEjecutivo(String cobhistNombreEjecutivo) {
		this.cobhistNombreEjecutivo = cobhistNombreEjecutivo;
	}

	@Column(name = "COBHIST_RESULTADO", length = 1000)
	public String getCobhistResultado() {
		return this.cobhistResultado;
	}

	public void setCobhistResultado(String cobhistResultado) {
		this.cobhistResultado = cobhistResultado;
	}

	@Column(name = "COBHIST_CANAL", length = 30)
	public String getCobhistCanal() {
		return this.cobhistCanal;
	}

	public void setCobhistCanal(String cobhistCanal) {
		this.cobhistCanal = cobhistCanal;
	}
	
	@Column(name = "COBHIST_PERSONA_CONTACTO", length = 50)
	public String getCobhistPersonaContacto() {
		return this.cobhistPersonaContacto;
	}

	public void setCobhistPersonaContacto(String cobhistPersonaContacto) {
		this.cobhistPersonaContacto = cobhistPersonaContacto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cbzGestionCobranzaHist")
	public Set<CbzResultadoArbolGestionModel> getCbzResultadoArbolGestions() {
		return this.cbzResultadoArbolGestions;
	}

	public void setCbzResultadoArbolGestions(Set<CbzResultadoArbolGestionModel> cbzResultadoArbolGestions) {
		this.cbzResultadoArbolGestions = cbzResultadoArbolGestions;
	}
	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cbzGestionCobranzaHist")
	public Set<CbzArbolGestionNotificacion> getCbzArbolGestionNotificacions() {
		return this.cbzArbolGestionNotificacions;
	}

	public void setCbzArbolGestionNotificacions(Set<CbzArbolGestionNotificacion> cbzArbolGestionNotificacions) {
		this.cbzArbolGestionNotificacions = cbzArbolGestionNotificacions;
	}

	@Column(name = "COBHIST_REQ_MOTORISTA", nullable = false, precision = 1, scale = 0)
	public boolean isCobhistReqMotorista() {
		return cobhistReqMotorista;
	}

	public void setCobhistReqMotorista(boolean cobhistReqMotorista) {
		this.cobhistReqMotorista = cobhistReqMotorista;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "COBHIST_FECHA_VISITA_MOTO", length = 7)
	public Date getCobhistFechaVisitaMoto() {
		return cobhistFechaVisitaMoto;
	}

	public void setCobhistFechaVisitaMoto(Date cobhistFechaVisitaMoto) {
		this.cobhistFechaVisitaMoto = cobhistFechaVisitaMoto;
	}

}
