package com.pdr.starter.cliente.model;
// Generated 03-09-2020 10:30:52 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CbzObenchCampos generated by hbm2java
 */
@Entity
@Table(name = "CBZ_OBENCH_CAMPOS", schema = "CBZPAR")
public class CbzObenchCamposModel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idCocCampos;
	private String cocDescripcion;
	private Boolean cocActivo;
	private String cocTipoProducto;
	private Set<CbzObenchParamModel> cbzObenchParams = new HashSet<CbzObenchParamModel>(0);

	public CbzObenchCamposModel() {
	}

	public CbzObenchCamposModel(long idCocCampos) {
		this.idCocCampos = idCocCampos;
	}

	public CbzObenchCamposModel(long idCocCampos, String cocDescripcion, Boolean cocActivo, String cocTipoProducto,
			Set<CbzObenchParamModel> cbzObenchParams) {
		this.idCocCampos = idCocCampos;
		this.cocDescripcion = cocDescripcion;
		this.cocActivo = cocActivo;
		this.cocTipoProducto = cocTipoProducto;
		this.cbzObenchParams = cbzObenchParams;
	}

	@Id

	@Column(name = "ID_COC_CAMPOS", unique = true, nullable = false, precision = 16, scale = 0)
	public long getIdCocCampos() {
		return this.idCocCampos;
	}

	public void setIdCocCampos(long idCocCampos) {
		this.idCocCampos = idCocCampos;
	}

	@Column(name = "COC_DESCRIPCION", length = 200)
	public String getCocDescripcion() {
		return this.cocDescripcion;
	}

	public void setCocDescripcion(String cocDescripcion) {
		this.cocDescripcion = cocDescripcion;
	}

	@Column(name = "COC_ACTIVO", precision = 1, scale = 0)
	public Boolean getCocActivo() {
		return this.cocActivo;
	}

	public void setCocActivo(Boolean cocActivo) {
		this.cocActivo = cocActivo;
	}

	@Column(name = "COC_TIPO_PRODUCTO", length = 25)
	public String getCocTipoProducto() {
		return this.cocTipoProducto;
	}

	public void setCocTipoProducto(String cocTipoProducto) {
		this.cocTipoProducto = cocTipoProducto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cbzObenchCampos")
	public Set<CbzObenchParamModel> getCbzObenchParams() {
		return this.cbzObenchParams;
	}

	public void setCbzObenchParams(Set<CbzObenchParamModel> cbzObenchParams) {
		this.cbzObenchParams = cbzObenchParams;
	}
}
