package com.pdr.starter.cliente.model;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Generated by BS2
 */
@Entity
@Table(name = "CBZ_SIMULACION_DOCUMENTOS", schema = "CBZPAR")
public class CbzSimulacionDocumentosModel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal idSimuDocumento;
	private CbzSimulacionModel cbzSimulacion;
	private CbzSimulacionTipoDocumentoModel cbzSimulacionTipoDocumento;

	public CbzSimulacionDocumentosModel() {
	}

	public CbzSimulacionDocumentosModel(BigDecimal idSimuDocumento, CbzSimulacionModel cbzSimulacion,
			CbzSimulacionTipoDocumentoModel cbzSimulacionTipoDocumento) {
		this.idSimuDocumento = idSimuDocumento;
		this.cbzSimulacion = cbzSimulacion;
		this.cbzSimulacionTipoDocumento = cbzSimulacionTipoDocumento;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id_sequence_documento")
	@SequenceGenerator(name = "id_sequence_documento", allocationSize = 1, sequenceName = "SEQ_SIMULACION_DOCUMENTOS", schema = "CBZPAR")
	@Column(name = "ID_SIMU_DOCUMENTO", unique = true, nullable = false, precision = 38, scale = 0)
	public BigDecimal getIdSimuDocumento() {
		return this.idSimuDocumento;
	}

	public void setIdSimuDocumento(BigDecimal idSimuDocumento) {
		this.idSimuDocumento = idSimuDocumento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_SIMULACION", nullable = false)
	public CbzSimulacionModel getCbzSimulacion() {
		return this.cbzSimulacion;
	}

	public void setCbzSimulacion(CbzSimulacionModel cbzSimulacion) {
		this.cbzSimulacion = cbzSimulacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_SIMU_TIPO_DOCUMENTO", nullable = false)
	public CbzSimulacionTipoDocumentoModel getCbzSimulacionTipoDocumento() {
		return this.cbzSimulacionTipoDocumento;
	}

	public void setCbzSimulacionTipoDocumento(CbzSimulacionTipoDocumentoModel cbzSimulacionTipoDocumento) {
		this.cbzSimulacionTipoDocumento = cbzSimulacionTipoDocumento;
	}

}
