package com.pdr.starter.cliente.model;
// Generated 23-07-2020 15:11:41 by Hibernate Tools 5.2.12.Final

import java.sql.Clob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;

/**
 * CbzSimulacionDocumentoImg generated by hbm2java
 */
@Entity
@Table(name = "CBZ_SIMULACION_DOCUMENTO_IMG", schema = "CBZPAR")
public class CbzSimulacionDocumentoImg implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idSimDocumentoImg;
	private String simDocimgDesc;
	
	@Lob
	private Clob simDocimgImg;

	public CbzSimulacionDocumentoImg() {
	}

	public CbzSimulacionDocumentoImg(int idSimDocumentoImg) {
		this.idSimDocumentoImg = idSimDocumentoImg;
	}

	public CbzSimulacionDocumentoImg(int idSimDocumentoImg, String simDocimgDesc, Clob simDocimgImg) {
		this.idSimDocumentoImg = idSimDocumentoImg;
		this.simDocimgDesc = simDocimgDesc;
		this.simDocimgImg = simDocimgImg;
	}

	@Id

	@Column(name = "ID_SIM_DOCUMENTO_IMG", unique = true, nullable = false, precision = 8, scale = 0)
	public int getIdSimDocumentoImg() {
		return this.idSimDocumentoImg;
	}

	public void setIdSimDocumentoImg(int idSimDocumentoImg) {
		this.idSimDocumentoImg = idSimDocumentoImg;
	}

	@Column(name = "SIM_DOCIMG_DESC", length = 100)
	public String getSimDocimgDesc() {
		return this.simDocimgDesc;
	}

	public void setSimDocimgDesc(String simDocimgDesc) {
		this.simDocimgDesc = simDocimgDesc;
	}

	@Column(name = "SIM_DOCIMG_IMG")
	public Clob getSimDocimgImg() {
		return this.simDocimgImg;
	}

	public void setSimDocimgImg(Clob simDocimgImg) {
		this.simDocimgImg = simDocimgImg;
	}

}
