package com.pdr.starter.cliente.model;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * generated by BS2
 */
@Entity
@Table(name = "CBZ_USER_CATALOGO_PGRE_TMP", schema = "CBZPAR")
public class CbzUserCatalogoPgreTmpModel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idUserCatalogoPgreTmp;
	private BigDecimal catpSec;
	private Date fechaAsignacion;
	private BigDecimal idUser;

	public CbzUserCatalogoPgreTmpModel() {
	}

	public CbzUserCatalogoPgreTmpModel(int idUserCatalogoPgreTmp, BigDecimal catpSec, Date fechaAsignacion) {
		this.idUserCatalogoPgreTmp = idUserCatalogoPgreTmp;
		this.catpSec = catpSec;
		this.fechaAsignacion = fechaAsignacion;
	}

	public CbzUserCatalogoPgreTmpModel(int idUserCatalogoPgreTmp, BigDecimal catpSec, Date fechaAsignacion,
			BigDecimal idUser) {
		this.idUserCatalogoPgreTmp = idUserCatalogoPgreTmp;
		this.catpSec = catpSec;
		this.fechaAsignacion = fechaAsignacion;
		this.idUser = idUser;
	}

	@Id

	@Column(name = "ID_USER_CATALOGO_PGRE_TMP", unique = true, nullable = false, precision = 8, scale = 0)
	public int getIdUserCatalogoPgreTmp() {
		return this.idUserCatalogoPgreTmp;
	}

	public void setIdUserCatalogoPgreTmp(int idUserCatalogoPgreTmp) {
		this.idUserCatalogoPgreTmp = idUserCatalogoPgreTmp;
	}

	@Column(name = "CATP_SEC", nullable = false, precision = 23, scale = 0)
	public BigDecimal getCatpSec() {
		return this.catpSec;
	}

	public void setCatpSec(BigDecimal catpSec) {
		this.catpSec = catpSec;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_ASIGNACION", nullable = false, length = 7)
	public Date getFechaAsignacion() {
		return this.fechaAsignacion;
	}

	public void setFechaAsignacion(Date fechaAsignacion) {
		this.fechaAsignacion = fechaAsignacion;
	}

	@Column(name = "ID_USER", precision = 21, scale = 0)
	public BigDecimal getIdUser() {
		return this.idUser;
	}

	public void setIdUser(BigDecimal idUser) {
		this.idUser = idUser;
	}

}
