package com.pdr.starter.cliente.model;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Generated by BS2
 */
@Entity
@Table(name = "SEG_POLIZAS_SEGUROS", schema = "SEGPAR", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "EMPR_COD", "CNCP_COD", "PERS_TIPO_ID_CIA", "PERS_ID_CIA", "EMPR_COD_BENE",
				"PLZA_FEC_INI", "PLZA_MANT_MODO", "PLZA_NUM" }),
		@UniqueConstraint(columnNames = { "PERS_TIPO_ID_CIA", "PERS_ID_CIA", "PLZA_NUM" }) })
public class SegPolizasSegurosModel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal plzaSec;
	private GenPersonasModel genPersonas;
	private GenEmpresasModel genEmpresasByEmprCod;
	private GenEmpresasModel genEmpresasByEmprCodBene;
	private String cncpCod;
	private String plzaMantModo;
	private BigDecimal plzaNum;
	private BigDecimal plzaKapiMax;
	private Short plzaEdadMaxIngr;
	private Integer plzaNumCuotMant;
	private Integer plzaNumMaxAseg;
	private Integer plzaNumCuotVenc;
	private Integer plzaPrdoSinNoti;
	private Integer plzaPrdoCaren;
	private String plzaPrdoCarenTipo;
	private String plzaIndNewAseg;
	private Date plzaFecIni;
	private Date plzaFecFin;
	private String plzaUserMod;
	private Date plzaFecMod;
	private Short plzaPrdoVtasNew;
	private String plzaIndIncorpAuto;

	public SegPolizasSegurosModel() {
	}

	public SegPolizasSegurosModel(BigDecimal plzaSec, GenEmpresasModel genEmpresasByEmprCod, GenEmpresasModel genEmpresasByEmprCodBene,
			String cncpCod, String plzaMantModo, BigDecimal plzaNum, Date plzaFecIni, String plzaUserMod,
			Date plzaFecMod) {
		this.plzaSec = plzaSec;
		this.genEmpresasByEmprCod = genEmpresasByEmprCod;
		this.genEmpresasByEmprCodBene = genEmpresasByEmprCodBene;
		this.cncpCod = cncpCod;
		this.plzaMantModo = plzaMantModo;
		this.plzaNum = plzaNum;
		this.plzaFecIni = plzaFecIni;
		this.plzaUserMod = plzaUserMod;
		this.plzaFecMod = plzaFecMod;
	}

	public SegPolizasSegurosModel(BigDecimal plzaSec, GenPersonasModel genPersonas, GenEmpresasModel genEmpresasByEmprCod,
			GenEmpresasModel genEmpresasByEmprCodBene, String cncpCod, String plzaMantModo, BigDecimal plzaNum,
			BigDecimal plzaKapiMax, Short plzaEdadMaxIngr, Integer plzaNumCuotMant, Integer plzaNumMaxAseg,
			Integer plzaNumCuotVenc, Integer plzaPrdoSinNoti, Integer plzaPrdoCaren, String plzaPrdoCarenTipo,
			String plzaIndNewAseg, Date plzaFecIni, Date plzaFecFin, String plzaUserMod, Date plzaFecMod,
			Short plzaPrdoVtasNew, String plzaIndIncorpAuto) {
		this.plzaSec = plzaSec;
		this.genPersonas = genPersonas;
		this.genEmpresasByEmprCod = genEmpresasByEmprCod;
		this.genEmpresasByEmprCodBene = genEmpresasByEmprCodBene;
		this.cncpCod = cncpCod;
		this.plzaMantModo = plzaMantModo;
		this.plzaNum = plzaNum;
		this.plzaKapiMax = plzaKapiMax;
		this.plzaEdadMaxIngr = plzaEdadMaxIngr;
		this.plzaNumCuotMant = plzaNumCuotMant;
		this.plzaNumMaxAseg = plzaNumMaxAseg;
		this.plzaNumCuotVenc = plzaNumCuotVenc;
		this.plzaPrdoSinNoti = plzaPrdoSinNoti;
		this.plzaPrdoCaren = plzaPrdoCaren;
		this.plzaPrdoCarenTipo = plzaPrdoCarenTipo;
		this.plzaIndNewAseg = plzaIndNewAseg;
		this.plzaFecIni = plzaFecIni;
		this.plzaFecFin = plzaFecFin;
		this.plzaUserMod = plzaUserMod;
		this.plzaFecMod = plzaFecMod;
		this.plzaPrdoVtasNew = plzaPrdoVtasNew;
		this.plzaIndIncorpAuto = plzaIndIncorpAuto;
	}

	@Id

	@Column(name = "PLZA_SEC", unique = true, nullable = false, precision = 23, scale = 0)
	public BigDecimal getPlzaSec() {
		return this.plzaSec;
	}

	public void setPlzaSec(BigDecimal plzaSec) {
		this.plzaSec = plzaSec;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "PERS_TIPO_ID_CIA", referencedColumnName = "PERS_TIPO_ID"),
			@JoinColumn(name = "PERS_ID_CIA", referencedColumnName = "PERS_ID") })
	public GenPersonasModel getGenPersonas() {
		return this.genPersonas;
	}

	public void setGenPersonas(GenPersonasModel genPersonas) {
		this.genPersonas = genPersonas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPR_COD", nullable = false)
	public GenEmpresasModel getGenEmpresasByEmprCod() {
		return this.genEmpresasByEmprCod;
	}

	public void setGenEmpresasByEmprCod(GenEmpresasModel genEmpresasByEmprCod) {
		this.genEmpresasByEmprCod = genEmpresasByEmprCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPR_COD_BENE", nullable = false)
	public GenEmpresasModel getGenEmpresasByEmprCodBene() {
		return this.genEmpresasByEmprCodBene;
	}

	public void setGenEmpresasByEmprCodBene(GenEmpresasModel genEmpresasByEmprCodBene) {
		this.genEmpresasByEmprCodBene = genEmpresasByEmprCodBene;
	}

	@Column(name = "CNCP_COD", nullable = false, length = 20)
	public String getCncpCod() {
		return this.cncpCod;
	}

	public void setCncpCod(String cncpCod) {
		this.cncpCod = cncpCod;
	}

	@Column(name = "PLZA_MANT_MODO", nullable = false, length = 20)
	public String getPlzaMantModo() {
		return this.plzaMantModo;
	}

	public void setPlzaMantModo(String plzaMantModo) {
		this.plzaMantModo = plzaMantModo;
	}

	@Column(name = "PLZA_NUM", nullable = false, precision = 20, scale = 0)
	public BigDecimal getPlzaNum() {
		return this.plzaNum;
	}

	public void setPlzaNum(BigDecimal plzaNum) {
		this.plzaNum = plzaNum;
	}

	@Column(name = "PLZA_KAPI_MAX", precision = 14)
	public BigDecimal getPlzaKapiMax() {
		return this.plzaKapiMax;
	}

	public void setPlzaKapiMax(BigDecimal plzaKapiMax) {
		this.plzaKapiMax = plzaKapiMax;
	}

	@Column(name = "PLZA_EDAD_MAX_INGR", precision = 3, scale = 0)
	public Short getPlzaEdadMaxIngr() {
		return this.plzaEdadMaxIngr;
	}

	public void setPlzaEdadMaxIngr(Short plzaEdadMaxIngr) {
		this.plzaEdadMaxIngr = plzaEdadMaxIngr;
	}

	@Column(name = "PLZA_NUM_CUOT_MANT", precision = 5, scale = 0)
	public Integer getPlzaNumCuotMant() {
		return this.plzaNumCuotMant;
	}

	public void setPlzaNumCuotMant(Integer plzaNumCuotMant) {
		this.plzaNumCuotMant = plzaNumCuotMant;
	}

	@Column(name = "PLZA_NUM_MAX_ASEG", precision = 5, scale = 0)
	public Integer getPlzaNumMaxAseg() {
		return this.plzaNumMaxAseg;
	}

	public void setPlzaNumMaxAseg(Integer plzaNumMaxAseg) {
		this.plzaNumMaxAseg = plzaNumMaxAseg;
	}

	@Column(name = "PLZA_NUM_CUOT_VENC", precision = 5, scale = 0)
	public Integer getPlzaNumCuotVenc() {
		return this.plzaNumCuotVenc;
	}

	public void setPlzaNumCuotVenc(Integer plzaNumCuotVenc) {
		this.plzaNumCuotVenc = plzaNumCuotVenc;
	}

	@Column(name = "PLZA_PRDO_SIN_NOTI", precision = 5, scale = 0)
	public Integer getPlzaPrdoSinNoti() {
		return this.plzaPrdoSinNoti;
	}

	public void setPlzaPrdoSinNoti(Integer plzaPrdoSinNoti) {
		this.plzaPrdoSinNoti = plzaPrdoSinNoti;
	}

	@Column(name = "PLZA_PRDO_CAREN", precision = 6, scale = 0)
	public Integer getPlzaPrdoCaren() {
		return this.plzaPrdoCaren;
	}

	public void setPlzaPrdoCaren(Integer plzaPrdoCaren) {
		this.plzaPrdoCaren = plzaPrdoCaren;
	}

	@Column(name = "PLZA_PRDO_CAREN_TIPO", length = 20)
	public String getPlzaPrdoCarenTipo() {
		return this.plzaPrdoCarenTipo;
	}

	public void setPlzaPrdoCarenTipo(String plzaPrdoCarenTipo) {
		this.plzaPrdoCarenTipo = plzaPrdoCarenTipo;
	}

	@Column(name = "PLZA_IND_NEW_ASEG", length = 2)
	public String getPlzaIndNewAseg() {
		return this.plzaIndNewAseg;
	}

	public void setPlzaIndNewAseg(String plzaIndNewAseg) {
		this.plzaIndNewAseg = plzaIndNewAseg;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PLZA_FEC_INI", nullable = false, length = 7)
	public Date getPlzaFecIni() {
		return this.plzaFecIni;
	}

	public void setPlzaFecIni(Date plzaFecIni) {
		this.plzaFecIni = plzaFecIni;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PLZA_FEC_FIN", length = 7)
	public Date getPlzaFecFin() {
		return this.plzaFecFin;
	}

	public void setPlzaFecFin(Date plzaFecFin) {
		this.plzaFecFin = plzaFecFin;
	}

	@Column(name = "PLZA_USER_MOD", nullable = false, length = 30)
	public String getPlzaUserMod() {
		return this.plzaUserMod;
	}

	public void setPlzaUserMod(String plzaUserMod) {
		this.plzaUserMod = plzaUserMod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PLZA_FEC_MOD", nullable = false, length = 7)
	public Date getPlzaFecMod() {
		return this.plzaFecMod;
	}

	public void setPlzaFecMod(Date plzaFecMod) {
		this.plzaFecMod = plzaFecMod;
	}

	@Column(name = "PLZA_PRDO_VTAS_NEW", precision = 3, scale = 0)
	public Short getPlzaPrdoVtasNew() {
		return this.plzaPrdoVtasNew;
	}

	public void setPlzaPrdoVtasNew(Short plzaPrdoVtasNew) {
		this.plzaPrdoVtasNew = plzaPrdoVtasNew;
	}

	@Column(name = "PLZA_IND_INCORP_AUTO", length = 2)
	public String getPlzaIndIncorpAuto() {
		return this.plzaIndIncorpAuto;
	}

	public void setPlzaIndIncorpAuto(String plzaIndIncorpAuto) {
		this.plzaIndIncorpAuto = plzaIndIncorpAuto;
	}

}
