package com.pdr.starter.cliente.model;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SegPlzaContId generated by SegPlzaContIdModel
 */
@Embeddable
public class SegPlzaContIdModel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BigDecimal plzaSec;
	private BigDecimal vtopCodCont;

	public SegPlzaContIdModel() {
	}

	public SegPlzaContIdModel(BigDecimal plzaSec, BigDecimal vtopCodCont) {
		this.plzaSec = plzaSec;
		this.vtopCodCont = vtopCodCont;
	}

	@Column(name = "PLZA_SEC", nullable = false, precision = 23, scale = 0)
	public BigDecimal getPlzaSec() {
		return this.plzaSec;
	}

	public void setPlzaSec(BigDecimal plzaSec) {
		this.plzaSec = plzaSec;
	}

	@Column(name = "VTOP_COD_CONT", nullable = false, precision = 23, scale = 0)
	public BigDecimal getVtopCodCont() {
		return this.vtopCodCont;
	}

	public void setVtopCodCont(BigDecimal vtopCodCont) {
		this.vtopCodCont = vtopCodCont;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SegPlzaContIdModel))
			return false;
		SegPlzaContIdModel castOther = (SegPlzaContIdModel) other;

		return ((this.getPlzaSec() == castOther.getPlzaSec()) || (this.getPlzaSec() != null
				&& castOther.getPlzaSec() != null && this.getPlzaSec().equals(castOther.getPlzaSec())))
				&& ((this.getVtopCodCont() == castOther.getVtopCodCont())
						|| (this.getVtopCodCont() != null && castOther.getVtopCodCont() != null
								&& this.getVtopCodCont().equals(castOther.getVtopCodCont())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPlzaSec() == null ? 0 : this.getPlzaSec().hashCode());
		result = 37 * result + (getVtopCodCont() == null ? 0 : this.getVtopCodCont().hashCode());
		return result;
	}

}
