package com.pdr.starter.cliente.model;

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * SegPlzaContModel generated by BS2
 */
@Entity
@Table(name = "SEG_PLZA_CONT", schema = "SEGPAR", uniqueConstraints = @UniqueConstraint(columnNames = { "VTOP_COD_CONT",
		"CNCP_COD" }))
public class SegPlzaContModel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private SegPlzaContIdModel id;
	private VtaContratosModel vtaContratos;
	private SegPolizasSegurosModel segPolizasSeguros;
	private String cncpCod;
	private Date plctFechIni;
	private String pzcoUserMod;
	private Date pzcoFecMod;

	public SegPlzaContModel() {
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "plzaSec", column = @Column(name = "PLZA_SEC", nullable = false, precision = 23, scale = 0)),
			@AttributeOverride(name = "vtopCodCont", column = @Column(name = "VTOP_COD_CONT", nullable = false, precision = 23, scale = 0)) })
	public SegPlzaContIdModel getId() {
		return this.id;
	}

	public void setId(SegPlzaContIdModel id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VTOP_COD_CONT", nullable = false, insertable = false, updatable = false)
	public VtaContratosModel getVtaContratos() {
		return this.vtaContratos;
	}

	public void setVtaContratos(VtaContratosModel vtaContratos) {
		this.vtaContratos = vtaContratos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PLZA_SEC", nullable = false, insertable = false, updatable = false)
	public SegPolizasSegurosModel getSegPolizasSeguros() {
		return this.segPolizasSeguros;
	}

	public void setSegPolizasSeguros(SegPolizasSegurosModel segPolizasSeguros) {
		this.segPolizasSeguros = segPolizasSeguros;
	}

	@Column(name = "CNCP_COD", nullable = false, length = 20)
	public String getCncpCod() {
		return this.cncpCod;
	}

	public void setCncpCod(String cncpCod) {
		this.cncpCod = cncpCod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PLCT_FECH_INI", nullable = false, length = 7)
	public Date getPlctFechIni() {
		return this.plctFechIni;
	}

	public void setPlctFechIni(Date plctFechIni) {
		this.plctFechIni = plctFechIni;
	}

	@Column(name = "PZCO_USER_MOD", length = 50)
	public String getPzcoUserMod() {
		return this.pzcoUserMod;
	}

	public void setPzcoUserMod(String pzcoUserMod) {
		this.pzcoUserMod = pzcoUserMod;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PZCO_FEC_MOD", nullable = false, length = 7)
	public Date getPzcoFecMod() {
		return this.pzcoFecMod;
	}

	public void setPzcoFecMod(Date pzcoFecMod) {
		this.pzcoFecMod = pzcoFecMod;
	}

}
